// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWAMzA3ZkdqEmpWxW49DZKkbTRV6JdEQ',
    appId: '1:358129211546:web:47ffd5d5f42e7f02786723',
    messagingSenderId: '358129211546',
    projectId: 'portfolio-5b7ea',
    authDomain: 'portfolio-5b7ea.firebaseapp.com',
    storageBucket: 'portfolio-5b7ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQDfrZ8u3QmRnHGvd7-MGT8djUf-nmUvw',
    appId: '1:358129211546:android:3521282de9d8957f786723',
    messagingSenderId: '358129211546',
    projectId: 'portfolio-5b7ea',
    storageBucket: 'portfolio-5b7ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASWiyqoZTOGnLv0JWY3gQjkF0ieWsM8OE',
    appId: '1:358129211546:ios:85647be65a7e2fd2786723',
    messagingSenderId: '358129211546',
    projectId: 'portfolio-5b7ea',
    storageBucket: 'portfolio-5b7ea.firebasestorage.app',
    iosBundleId: 'com.example.amalportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASWiyqoZTOGnLv0JWY3gQjkF0ieWsM8OE',
    appId: '1:358129211546:ios:85647be65a7e2fd2786723',
    messagingSenderId: '358129211546',
    projectId: 'portfolio-5b7ea',
    storageBucket: 'portfolio-5b7ea.firebasestorage.app',
    iosBundleId: 'com.example.amalportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChWAMzA3ZkdqEmpWxW49DZKkbTRV6JdEQ',
    appId: '1:358129211546:web:35074bb6326b64c9786723',
    messagingSenderId: '358129211546',
    projectId: 'portfolio-5b7ea',
    authDomain: 'portfolio-5b7ea.firebaseapp.com',
    storageBucket: 'portfolio-5b7ea.firebasestorage.app',
  );
}
